### PR TITLE
Fix error happening when using with rest assignment

### LINKED ISSUE #1: Error when using rest assignment
I'm getting the following error when I have an arrow function inside a component like this:

```
ArrowFunctionExpression Error TypeError: Property value expected type of string but got null
[webpack]     at Object.validate (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\types\lib\definitions\utils.js:164:13)
[webpack]     at validateField (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\types\lib\validators\validate.js:22:9)
[webpack]     at validate (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\types\lib\validators\validate.js:16:3)
[webpack]     at builder (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\types\lib\builders\builder.js:38:27)
[webpack]     at Object.StringLiteral (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\types\lib\builders\generated\index.js:337:31)
[webpack]     at handleFunctionExpression (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\babel-plugin-set-display-name\lib\index.js:15:804)
[webpack]     at ArrowFunctionExpression (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\babel-plugin-set-display-name\lib\index.js:37:11)
[webpack]     at NodePath._call (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\path\context.js:53:20)
[webpack]     at NodePath.call (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\path\context.js:40:17)
[webpack]     at NodePath.visit (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\path\context.js:88:12)
[webpack]     at TraversalContext.visitQueue (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\context.js:112:16)
[webpack]     at TraversalContext.visitMultiple (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\context.js:79:17)
[webpack]     at TraversalContext.visit (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\context.js:138:19)
[webpack]     at Function.traverse.node (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\index.js:80:17)
[webpack]     at NodePath.visit (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\path\context.js:95:18)
[webpack]     at TraversalContext.visitQueue (C:\_Git\Hireahelper\src\Hireahelper.Web.React\node_modules\@babel\traverse\lib\context.js:112:16) NodePath {
```

Here is example:
```
const Component = ()=> {

const { x } = useSelector(state=> state.foo);

return <div>{x}</div>;

}

### PR DESCRIPTION
**Pull request by coolkev**
fixes #1

### CODE REVIEW

**Comment by coolkev** [comment]
Hi @davidbonnet I love the plugin, but am running into this issue. I'm pretty sure my fix is pretty safe - would you consider merging this PR and pushing an update to the package?

**Comment by davidbonnet** [comment]
Thanks @coolkev for reporting and fixing this. Sorry for the delay. I'll add a test and deploy shortly.

**Comment by davidbonnet** [comment]
@coolkev: Deployed.

**Comment by coolkev** [comment]
Worked perfectly. Thanks!

**Pull request merged**
